#pragma once
#define _CRT_SECURE_NO_WARNINGS
#include "log.h"
#include "ptr.h"
#include "profiling_label.h"
#include "other.h"
#include "vulkan/vulkan.hpp"
#include <vector>
#include <array>
#include <stdint.h>
#include "sizes.h"